# Generated by Django 4.2 on 2024-11-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projecttype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
